# Generated by Django 4.2 on 2023-05-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('intensity', models.IntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('insight', models.CharField(max_length=100)),
                ('end_Year', models.DateField(default='')),
                ('region', models.CharField(max_length=100)),
                ('start_Year', models.DateField(default='')),
                ('impact', models.CharField(default='', max_length=100)),
                ('added', models.DateTimeField()),
                ('published', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('relevance', models.IntegerField()),
                ('pestle', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='DashboardData',
        ),
    ]
