# Generated by Django 4.2 on 2023-05-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_visual_delete_dashboarddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visual',
            name='added',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='visual',
            name='end_Year',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='visual',
            name='intensity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visual',
            name='published',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='visual',
            name='start_Year',
            field=models.CharField(default='', max_length=100),
        ),
    ]
