# Generated by Django 4.2 on 2023-05-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_visual_added_alter_visual_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visual',
            name='relevance',
            field=models.CharField(max_length=100),
        ),
    ]
