# Generated by Django 4.2 on 2023-05-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_visual_relevance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visual',
            new_name='Visual_dash',
        ),
    ]
