# Generated by Django 4.2 on 2023-05-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_visual_visual_dash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visual_dash',
            name='end_Year',
        ),
    ]
