# Generated by Django 4.2 on 2023-05-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_visual_dash_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual_dash',
            name='likelihood',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
